TOKEN: Telegram_token   #*обязательный
PASSWORD: '12345678' #*обязательный, пароль от бота в телеграм
ADMIN_PASSWORD: '87654321' #админ пароль от бота в телеграм
SOCKET_IP: 0.0.0.0 #адрес, на котором запускается socket_server
SOCKET_PORT: 3000 #порт, на котором запускается socket_server
SOCKET_PASS: '1111' #*обязательный, пароль для подключения к socket_server, должен совпадать с S_PASS в bot.py
LOG_LEVEL: INFO
DEVICE_ADDRESS: 46 #адрес опрашиваемого счетчика, с завода последние цифры серийного номера
DEVICE_PASSWORD: '000000' #пароль опрашиваемого счетчика, с завода 
DEVICE_A: 1250 #постоянная счетчика, написана на счетчике
DEVICE_Kc: 2 #постоянная счетчика, из руководства, в большинстве слуаев равна 1
DEVICE_Ktt: '80/4' #коэффициент трансформации ТТ
DEVICE_Ktn: '220/220' #коэффициент трансформации ТН
SIM_PHONE: '+79611111111' #номер сим карты модема
